### ISSUE TITLE
TypeError: function() got an unexpected keyword argument 'sample'

### ISSUE THREAD

**Issue by blhl** [kearnz/autoimpute#30]
Hi. I am interested in dealing with missing values and found your efforts very valuable. However, I just started by copying the code of Tutorial Part 1 from the link:
https://kearnz.github.io/autoimpute-tutorials/
and while I have been trying to run it I got the following error"
Traceback (most recent call last):
  File "Imp_Autoimpute_2.py", line 61, in <module>
    data_imputed_once = SingleImputer().fit_transform(data_miss)
  File "/home/baligh/.local/lib/python3.7/site-packages/autoimpute/imputations/dataframe/single_imputer.py", line 275, in fit_transform
    return self.fit(X, y).transform(X)
  File "/home/baligh/.local/lib/python3.7/site-packages/autoimpute/utils/checks.py", line 61, in wrapper
    return func(d, *args, **kwargs)
  File "/home/baligh/.local/lib/python3.7/site-packages/autoimpute/utils/checks.py", line 126, in wrapper
    return func(d, *args, **kwargs)
  File "/home/baligh/.local/lib/python3.7/site-packages/autoimpute/utils/checks.py", line 173, in wrapper
    return func(d, *args, **kwargs)
  File "/home/baligh/.local/lib/python3.7/site-packages/autoimpute/imputations/dataframe/single_imputer.py", line 261, in transform
    X.loc[imp_ix, column] = imputer.impute(x_)
  File "/home/baligh/.local/lib/python3.7/site-packages/autoimpute/imputations/series/default.py", line 400, in impute
    X_ = super().impute(X)
  File "/home/baligh/.local/lib/python3.7/site-packages/autoimpute/imputations/series/default.py", line 214, in impute
    X_ = imp.impute(X)
  File "/home/baligh/.local/lib/python3.7/site-packages/autoimpute/imputations/series/pmm.py", line 155, in impute
    init=self.init,
  File "/usr/pkg/lib/python3.7/site-packages/pymc3/sampling.py", line 396, in sample
    progressbar=progressbar, **kwargs)
  File "/usr/pkg/lib/python3.7/site-packages/pymc3/sampling.py", line 1515, in init_nuts
    step = pm.NUTS(potential=potential, model=model, **kwargs)
  File "/usr/pkg/lib/python3.7/site-packages/pymc3/step_methods/hmc/nuts.py", line 152, in __init__
    super().__init__(vars, **kwargs)
  File "/usr/pkg/lib/python3.7/site-packages/pymc3/step_methods/hmc/base_hmc.py", line 72, in __init__
    super().__init__(vars, blocked=blocked, model=model, dtype=dtype, **theano_kwargs)
  File "/usr/pkg/lib/python3.7/site-packages/pymc3/step_methods/arraystep.py", line 228, in __init__
    vars, dtype=dtype, **theano_kwargs)
  File "/usr/pkg/lib/python3.7/site-packages/pymc3/model.py", line 723, in logp_dlogp_function
    return ValueGradFunction(self.logpt, grad_vars, extra_vars, **kwargs)
  File "/usr/pkg/lib/python3.7/site-packages/pymc3/model.py", line 462, in __init__
    inputs, [self._cost_joined, grad], givens=givens, **kwargs)
TypeError: function() got an unexpected keyword argument 'sample'

Best,
Bal.

**Comment by kearnz** [comment]
Hi @blhl 

This issue seems identical to those that have been raised before. [Please see the following](https://github.com/kearnz/autoimpute/issues/27) for more information and **let me know if it resolves your issue.**

Essentially, you need to make sure you have versions of `autoimpute` and `pymc3` that are compatible. `autoimpute` 0.11.5 works with `pymc3` 3.5, 3.6, and 3.7. Earlier versions of `autoimpute`, however, do not work with `pymc3` 3.7. 

I just tested this to confirm in a virtual environment and everything seems to work as expected.

Best,
Joe

**Comment by blhl** [comment]
Many thanks, Joe for your kind and helpful reply. 
It is working now.
And sorry for this inconvenience, I should've checked the other issues before creating this. 
Thanks again,
Bal.

**Comment by kearnz** [comment]
no worries, glad it's working!

**Comment by blhl** [comment]
By the way, could you please let me know how you prefer your package to be cited?

**Comment by kearnz** [comment]
I'll update the README with citation info.
