### ISSUE TITLE
MultipleImputer transform error 

### ISSUE THREAD

**Issue by sungreong** [kearnz/autoimpute#27]
hi I want to use autoimpute package.
so I test it. but it is not worked.
how to solve it? 

```
sample = data.sample(1000)
mi.fit(sample)
mi = MultipleImputer(return_list= True) 
imputed = mi.transform(sample)
```
error 
```
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-41db8ffcd4a8> in <module>
----> 1 imputed = mi.transform(sample)

~/anaconda3/envs/py36/lib/python3.6/site-packages/autoimpute/utils/checks.py in wrapper(d, *args, **kwargs)
     59             err = f"Neither {d_err} nor {a_err} are of type pd.DataFrame"
     60             raise TypeError(err)
---> 61         return func(d, *args, **kwargs)
     62     return wrapper
     63 

~/anaconda3/envs/py36/lib/python3.6/site-packages/autoimpute/utils/checks.py in wrapper(d, *args, **kwargs)
    124 
    125         # return func if no missingness violations detected, then return wrap
--> 126         return func(d, *args, **kwargs)
    127     return wrapper
    128 

~/anaconda3/envs/py36/lib/python3.6/site-packages/autoimpute/utils/checks.py in wrapper(d, *args, **kwargs)
    171             err = f"All values missing in column(s) {nc}. Should be removed."
    172             raise ValueError(err)
--> 173         return func(d, *args, **kwargs)
    174     return wrapper
    175 

~/anaconda3/envs/py36/lib/python3.6/site-packages/autoimpute/imputations/dataframe/multiple_imputer.py in transform(self, X)
    224                    for i in self.statistics_.items())
    225         if self.return_list:
--> 226             imputed = list(imputed)
    227         return imputed
    228 

~/anaconda3/envs/py36/lib/python3.6/site-packages/autoimpute/imputations/dataframe/multiple_imputer.py in <genexpr>(.0)
    222         # sequential only for now
    223         imputed = ((i[0], i[1].transform(X))
--> 224                    for i in self.statistics_.items())
    225         if self.return_list:
    226             imputed = list(imputed)

~/anaconda3/envs/py36/lib/python3.6/site-packages/autoimpute/utils/checks.py in wrapper(d, *args, **kwargs)
     59             err = f"Neither {d_err} nor {a_err} are of type pd.DataFrame"
     60             raise TypeError(err)
---> 61         return func(d, *args, **kwargs)
     62     return wrapper
     63 

~/anaconda3/envs/py36/lib/python3.6/site-packages/autoimpute/utils/checks.py in wrapper(d, *args, **kwargs)
    124 
    125         # return func if no missingness violations detected, then return wrap
--> 126         return func(d, *args, **kwargs)
    127     return wrapper
    128 

~/anaconda3/envs/py36/lib/python3.6/site-packages/autoimpute/utils/checks.py in wrapper(d, *args, **kwargs)
    171             err = f"All values missing in column(s) {nc}. Should be removed."
    172             raise ValueError(err)
--> 173         return func(d, *args, **kwargs)
    174     return wrapper
    175 

~/anaconda3/envs/py36/lib/python3.6/site-packages/autoimpute/imputations/dataframe/single_imputer.py in transform(self, X)
    259 
    260             # perform imputation given the specified imputer and value for x_
--> 261             X.loc[imp_ix, column] = imputer.impute(x_)
    262         return X
    263 

~/anaconda3/envs/py36/lib/python3.6/site-packages/autoimpute/imputations/series/default.py in impute(self, X)
    398     def impute(self, X):
    399         """Defer transform to the DefaultBaseImputer."""
--> 400         X_ = super().impute(X)
    401         return X_

~/anaconda3/envs/py36/lib/python3.6/site-packages/autoimpute/imputations/series/default.py in impute(self, X)
    212         # ensure that param is not none, which indicates time series column
    213         if imp:
--> 214             X_ = imp.impute(X)
    215             return X_
    216 

~/anaconda3/envs/py36/lib/python3.6/site-packages/autoimpute/imputations/series/pmm.py in impute(self, X)
    153                 sample=self.sample,
    154                 tune=self.tune,
--> 155                 init=self.init,
    156             )
    157         self.trace_ = tr

~/anaconda3/envs/py36/lib/python3.6/site-packages/pymc3/sampling.py in sample(draws, step, init, n_init, start, trace, chain_idx, chains, cores, tune, progressbar, model, random_seed, discard_tuned_samples, compute_convergence_checks, **kwargs)
    394                 start_, step = init_nuts(init=init, chains=chains, n_init=n_init,
    395                                          model=model, random_seed=random_seed,
--> 396                                          progressbar=progressbar, **kwargs)
    397                 if start is None:
    398                     start = start_

~/anaconda3/envs/py36/lib/python3.6/site-packages/pymc3/sampling.py in init_nuts(init, chains, n_init, model, random_seed, progressbar, **kwargs)
   1513             'Unknown initializer: {}.'.format(init))
   1514 
-> 1515     step = pm.NUTS(potential=potential, model=model, **kwargs)
   1516 
   1517     return start, step

~/anaconda3/envs/py36/lib/python3.6/site-packages/pymc3/step_methods/hmc/nuts.py in __init__(self, vars, max_treedepth, early_max_treedepth, **kwargs)
    150         `pm.sample` to the desired number of tuning steps.
    151         """
--> 152         super().__init__(vars, **kwargs)
    153 
    154         self.max_treedepth = max_treedepth

~/anaconda3/envs/py36/lib/python3.6/site-packages/pymc3/step_methods/hmc/base_hmc.py in __init__(self, vars, scaling, step_scale, is_cov, model, blocked, potential, dtype, Emax, target_accept, gamma, k, t0, adapt_step_size, step_rand, **theano_kwargs)
     70         vars = inputvars(vars)
     71 
---> 72         super().__init__(vars, blocked=blocked, model=model, dtype=dtype, **theano_kwargs)
     73 
     74         self.adapt_step_size = adapt_step_size

~/anaconda3/envs/py36/lib/python3.6/site-packages/pymc3/step_methods/arraystep.py in __init__(self, vars, model, blocked, dtype, **theano_kwargs)
    226 
    227         func = model.logp_dlogp_function(
--> 228             vars, dtype=dtype, **theano_kwargs)
    229 
    230         # handle edge case discovered in #2948

~/anaconda3/envs/py36/lib/python3.6/site-packages/pymc3/model.py in logp_dlogp_function(self, grad_vars, **kwargs)
    721         varnames = [var.name for var in grad_vars]
    722         extra_vars = [var for var in self.free_RVs if var.name not in varnames]
--> 723         return ValueGradFunction(self.logpt, grad_vars, extra_vars, **kwargs)
    724 
    725     @property

~/anaconda3/envs/py36/lib/python3.6/site-packages/pymc3/model.py in __init__(self, cost, grad_vars, extra_vars, dtype, casting, **kwargs)
    460 
    461         self._theano_function = theano.function(
--> 462             inputs, [self._cost_joined, grad], givens=givens, **kwargs)
    463 
    464     def set_extra_values(self, extra_vars):

**TypeError: function() got an unexpected keyword argument 'sample'**

```

**Comment by kearnz** [comment]
Hi, 

First, the `MultipleImputer` successfully fits the data. The error is raised during the `transform` step. Because you did not provide a `strategy`, the imputer uses `pmm` by default. Under the hood, `pmm` utilizes the `pymc3` package. Looking at the traceback, the error indicates that pymc3 is calling theano.function, and passing `'sample'` (your data) as an keyword argument. theano.function does not take `'sample'` as an argument, so an error is thrown. 

I haven't seen this happen before, and I have not been able to recreate the situation on my end at this point. Can you provide more information about what computer you're using? What version of python and what dependencies for packages? Additionally, can you provide more info on what your `sample` data is? (i.e. the features, columns, etc.)

For reference, I'm using MacOS High Sierra 10.13.6, and I use Anaconda distribution with python 3.6

The following code runs with no errors on my computer:
```python
import numpy as np
import pandas as pd
from scipy.stats import norm, binom
from autoimpute.imputations import MultipleImputer

# seed to follow along
np.random.seed(654654)

# generate 1500 data points
N = np.arange(1500)

# create correlated, heteroskedastic random variables
a, b = 0, 1
eps = np.array([norm(0, n).rvs() for n in N])
y = (a + b*N + eps) / 100                         
x = (N + norm(10, 10).rvs(len(N))) / 100
 
# 30% missingness created artificially
y[binom(1, 0.3).rvs(len(N)) == 1] = np.nan

# collect results in a dataframe 
data = pd.DataFrame({"y": y, "x": x})
sample = data.sample(1000)

# imputation
imp = MultipleImputer(return_list=True)
imp.fit(sample)
imputed = imp.transform(sample)
```

Let me know if this code works for you, and from there if I can help.

**Comment by JeanBaptisteScellier** [comment]
Hello,

I'm facing the same problem as sungreong. I tried your code on my machine and I got exactly the same error as described.
I'm using Anaconda distribution with Python 3.7.3 and my computer uses Windows Server 2016 Datacenter.

I would be glad to have a solution. This library looks cool though complex :)

**Comment by JeanBaptisteScellier** [comment]
Hello,

I just tried your code again with Google Colab and got the same error. Colab uses Python 3.6.8 on linux.

**Comment by fajerbolt** [comment]
Hello,

I have the same problem as above. The problem doesn't occur with some of the strategies (like norm and mean) but occurs with others (like pmm). 
I'm using Anaconda distribution with Python 3.6 on MacOS Mojave 10.14.6

**Comment by kearnz** [comment]
Hi @sungreong @JeanBaptisteScellier @fajerbolt,

I was able to recreate the issue on my side. It seems to have to do with the version of pymc3 you are using. `autoimpute` is built using pymc3 v3.5 (although it also works with v3.6). 

To test this, I created a virtual environment locally and installed `autoimpute`. I then installed its dependencies from the `requirements.txt` file. Next, I ran the sample code I provided above, and everything worked fine.

Outside of the virtualenv, I upgraded my global version of pymc3 to v3.7. When I reran the exact same code, I received the error you have all experienced : `**TypeError: function() got an unexpected keyword argument 'sample'**`.

**In the short term, I'd recommend using autoimpute with pymc3 3.5 or 3.6** if you want to use any of the bayesian methods (including pmm). Otherwise (as @fajerbolt noted), the package should work fine for other strategies.

When I have time, I'm going to look into what's causing `autoimpute` code to break with new versions of pymc3. Ideally I'll have a fix out soon.

**Comment by JeanBaptisteScellier** [comment]
Thank you for your help.

It worked well on Google Colab. On Windows though I got this error:

`TypeError                                 Traceback (most recent call last)
<ipython-input-1-c799dbc0842c> in <module>
     26 imp = MultipleImputer(return_list=True)
     27 imp.fit(sample)
---> 28 imputed = imp.transform(sample)

C:\ProgramData\Anaconda3\lib\site-packages\autoimpute\utils\checks.py in wrapper(d, *args, **kwargs)
     59             err = f"Neither {d_err} nor {a_err} are of type pd.DataFrame"
     60             raise TypeError(err)
---> 61         return func(d, *args, **kwargs)
     62     return wrapper
     63 

C:\ProgramData\Anaconda3\lib\site-packages\autoimpute\utils\checks.py in wrapper(d, *args, **kwargs)
    124 
    125         # return func if no missingness violations detected, then return wrap
--> 126         return func(d, *args, **kwargs)
    127     return wrapper
    128 

C:\ProgramData\Anaconda3\lib\site-packages\autoimpute\utils\checks.py in wrapper(d, *args, **kwargs)
    171             err = f"All values missing in column(s) {nc}. Should be removed."
    172             raise ValueError(err)
--> 173         return func(d, *args, **kwargs)
    174     return wrapper
    175 

C:\ProgramData\Anaconda3\lib\site-packages\autoimpute\imputations\dataframe\multiple_imputer.py in transform(self, X)
    224                    for i in self.statistics_.items())
    225         if self.return_list:
--> 226             imputed = list(imputed)
    227         return imputed
    228 

C:\ProgramData\Anaconda3\lib\site-packages\autoimpute\imputations\dataframe\multiple_imputer.py in <genexpr>(.0)
    222         # sequential only for now
    223         imputed = ((i[0], i[1].transform(X))
--> 224                    for i in self.statistics_.items())
    225         if self.return_list:
    226             imputed = list(imputed)

C:\ProgramData\Anaconda3\lib\site-packages\autoimpute\utils\checks.py in wrapper(d, *args, **kwargs)
     59             err = f"Neither {d_err} nor {a_err} are of type pd.DataFrame"
     60             raise TypeError(err)
---> 61         return func(d, *args, **kwargs)
     62     return wrapper
     63 

C:\ProgramData\Anaconda3\lib\site-packages\autoimpute\utils\checks.py in wrapper(d, *args, **kwargs)
    124 
    125         # return func if no missingness violations detected, then return wrap
--> 126         return func(d, *args, **kwargs)
    127     return wrapper
    128 

C:\ProgramData\Anaconda3\lib\site-packages\autoimpute\utils\checks.py in wrapper(d, *args, **kwargs)
    171             err = f"All values missing in column(s) {nc}. Should be removed."
    172             raise ValueError(err)
--> 173         return func(d, *args, **kwargs)
    174     return wrapper
    175 

C:\ProgramData\Anaconda3\lib\site-packages\autoimpute\imputations\dataframe\single_imputer.py in transform(self, X)
    259 
    260             # perform imputation given the specified imputer and value for x_
--> 261             X.loc[imp_ix, column] = imputer.impute(x_)
    262         return X
    263 

C:\ProgramData\Anaconda3\lib\site-packages\autoimpute\imputations\series\default.py in impute(self, X)
    398     def impute(self, X):
    399         """Defer transform to the DefaultBaseImputer."""
--> 400         X_ = super().impute(X)
    401         return X_

C:\ProgramData\Anaconda3\lib\site-packages\autoimpute\imputations\series\default.py in impute(self, X)
    212         # ensure that param is not none, which indicates time series column
    213         if imp:
--> 214             X_ = imp.impute(X)
    215             return X_
    216 

C:\ProgramData\Anaconda3\lib\site-packages\autoimpute\imputations\series\pmm.py in impute(self, X)
    153                 sample=self.sample,
    154                 tune=self.tune,
--> 155                 init=self.init,
    156             )
    157         self.trace_ = tr

C:\ProgramData\Anaconda3\lib\site-packages\pymc3\sampling.py in sample(draws, step, init, n_init, start, trace, chain_idx, chains, cores, tune, nuts_kwargs, step_kwargs, progressbar, model, random_seed, live_plot, discard_tuned_samples, live_plot_kwargs, compute_convergence_checks, use_mmap, **kwargs)
    437             _print_step_hierarchy(step)
    438             try:
--> 439                 trace = _mp_sample(**sample_args)
    440             except pickle.PickleError:
    441                 _log.warning("Could not pickle model, sampling singlethreaded.")

C:\ProgramData\Anaconda3\lib\site-packages\pymc3\sampling.py in _mp_sample(draws, tune, step, chains, cores, chain, random_seed, start, progressbar, trace, model, use_mmap, **kwargs)
    984         sampler = ps.ParallelSampler(
    985             draws, tune, chains, cores, random_seed, start, step,
--> 986             chain, progressbar)
    987         try:
    988             try:

C:\ProgramData\Anaconda3\lib\site-packages\pymc3\parallel_sampling.py in __init__(self, draws, tune, chains, cores, seeds, start_points, step_method, start_chain_num, progressbar)
    311                 draws, tune, step_method, chain + start_chain_num, seed, start
    312             )
--> 313             for chain, seed, start in zip(range(chains), seeds, start_points)
    314         ]
    315 

C:\ProgramData\Anaconda3\lib\site-packages\pymc3\parallel_sampling.py in <listcomp>(.0)
    311                 draws, tune, step_method, chain + start_chain_num, seed, start
    312             )
--> 313             for chain, seed, start in zip(range(chains), seeds, start_points)
    314         ]
    315 

C:\ProgramData\Anaconda3\lib\site-packages\pymc3\parallel_sampling.py in __init__(self, draws, tune, step_method, chain, seed, start)
    202         )
    203         # We fork right away, so that the main process can start tqdm threads
--> 204         self._process.start()
    205 
    206     @property

C:\ProgramData\Anaconda3\lib\multiprocessing\process.py in start(self)
    110                'daemonic processes are not allowed to have children'
    111         _cleanup()
--> 112         self._popen = self._Popen(self)
    113         self._sentinel = self._popen.sentinel
    114         # Avoid a refcycle if the target function holds an indirect

C:\ProgramData\Anaconda3\lib\multiprocessing\context.py in _Popen(process_obj)
    221     @staticmethod
    222     def _Popen(process_obj):
--> 223         return _default_context.get_context().Process._Popen(process_obj)
    224 
    225 class DefaultContext(BaseContext):

C:\ProgramData\Anaconda3\lib\multiprocessing\context.py in _Popen(process_obj)
    320         def _Popen(process_obj):
    321             from .popen_spawn_win32 import Popen
--> 322             return Popen(process_obj)
    323 
    324     class SpawnContext(BaseContext):

C:\ProgramData\Anaconda3\lib\multiprocessing\popen_spawn_win32.py in __init__(self, process_obj)
     87             try:
     88                 reduction.dump(prep_data, to_child)
---> 89                 reduction.dump(process_obj, to_child)
     90             finally:
     91                 set_spawning_popen(None)

C:\ProgramData\Anaconda3\lib\multiprocessing\reduction.py in dump(obj, file, protocol)
     58 def dump(obj, file, protocol=None):
     59     '''Replacement for pickle.dump() using ForkingPickler.'''
---> 60     ForkingPickler(file, protocol).dump(obj)
     61 
     62 #

TypeError: can't pickle fortran objects`

**Comment by kearnz** [comment]
Unfortunately this is a known issue with Windows. I've put a section in the bottom of my README addressing the problem. It's titled _A Note for Windows Users:_

I was able to solve the problem on Windows by running posterior sampling on one core only, although this slows down the process of bayesian methods significantly. That being said, you can use multiprocessing with the `SingleImputer` and essentially mimic the behavior of the `MultipleImputer`. Doing so is actually faster if you plan to do a large number of imputations.

The note above is generally out of scope for most users, so I don't have any further info documented about it. If that's of interest let me know.

**Comment by JeanBaptisteScellier** [comment]
OK, thank you very much! I will read your note.

**Comment by kearnz** [comment]
Sounds good! Closing the issue now.
